### ISSUE TITLE
sensible.waitFor does not return completed extraction

### ISSUE THREAD

**Issue by tchbw** [sensible-hq/sensible-api-js#4]
Hey team,

We're no longer getting consistent completed extraction results from `sensible.waitFor`. The response we receive now nearly always is an extraction in the `PROCESSING` state whereas we used to always get a completed extraction result. 

I'm not sure if this is a new state that was added, but looking at [the definition](https://github.com/sensible-hq/sensible-api-js/blob/ea5c97399319bb200c797a4c8badbde354fcda2a/src/index.ts#L119-L149) of `waitFor`, it looks like the method simply waits for the extraction to move out of a `WAITING` state. The docs imply that `waitFor` should return a completed transaction though.

Our extraction function is very similar to the example code and worked in the past:
```
async function extractUsingSensible<T extends ZodSchema>({
  documentType,
  responseSchema,
  documentBuffer,
}: {
  documentType: string;
  responseSchema: T;
  documentBuffer: Buffer;
}): Promise<z.infer<T> | null> {
  const start = Date.now();
  try {
    const sensible = new SensibleSDK(env.SENSIBLE_API_KEY); //replace with your API key
    const request = await sensible.extract({
      file: documentBuffer,
      documentType,
      environment: env.SENSIBLE_ENVIRONMENT,
    });
    const results = await sensible.waitFor(request); // polls every 5 seconds. Optional if you configure a webhook
    console.log(`Response from sensible: ${JSON.stringify(results, null, 2)}`);
    // eslint-disable-next-line @typescript-eslint/no-unsafe-return
    return responseSchema.parse(results);
  } catch (err) {
    console.error(`Sensible extraction failed`, err);
    throw err;
  } finally {
    console.log(
      `Sensible extraction took`,
      `${(Date.now() - start) / 1000} seconds`
    );
  }
}
```

And this is the result returned from `sensible.waitFor`:
```
[next] [Apr 7 11:02:42 PM UTC] INFO (console): Response from sensible: {
[next]   "id": "f680d841-f682-4149-abe5-04853257f4a8",
[next]   "created": "2024-04-07T23:02:36.816Z",
[next]   "status": "PROCESSING",
[next]   "type": "certificate_of_incorporation",
[next]   "environment": "development",
[next]   "errors": [],
[next]   "download_url": REDACTED
[next] }
```

Could you let us know if there's been some regression? Appreciate the help, thanks!

**Comment by horacio-penya** [comment]
Solved in v0.0.10.
